POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "halo2",
    "password": "halo2"
}  
###
POST http://localhost:3001/register
Content-Type: application/json

{
    "username": "sayabadut",
    "password": "tolongsaya",
    "name" : "badut",
    "confirmPassword": "tolongsaya"
} 

###
GET http://localhost:3001/self
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzdkMTQyNS02N2Q0LTQ0NzgtOGJmNy04YWMwZGQyYjEzYzgiLCJ1c2VybmFtZSI6ImhhbG8yIiwiaWF0IjoxNjkwMDg0ODkxfQ.W6cmbCOP_7wwgtnerJ4duAatm1D2xMyZAQ9cXN_egRg

###
POST http://localhost:3001/barang
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzdkMTQyNS02N2Q0LTQ0NzgtOGJmNy04YWMwZGQyYjEzYzgiLCJ1c2VybmFtZSI6ImhhbG8yIiwiaWF0IjoxNjkwMDg5ODI2fQ.BBpZfdxfJcewksBvTVrScrm9V9Xrsf5f1xOa5Aic-hU

{
    "nama" : "barang0",
    "harga" : 1000,
    "stok" : 20,
    "perusahaan_id" : "ABC",
    "kode" : "DEH"
}

###
GET http://localhost:3001/barang/f77a1262-cd96-4eb7-81cf-58574ad32875
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzdkMTQyNS02N2Q0LTQ0NzgtOGJmNy04YWMwZGQyYjEzYzgiLCJ1c2VybmFtZSI6ImhhbG8yIiwiaWF0IjoxNjkwMDg5ODI2fQ.BBpZfdxfJcewksBvTVrScrm9V9Xrsf5f1xOa5Aic-hU

###
POST http://localhost:3000/barang/7e2e34d0-fa7f-47c1-9d88-eaa2af48b288
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzdkMTQyNS02N2Q0LTQ0NzgtOGJmNy04YWMwZGQyYjEzYzgiLCJ1c2VybmFtZSI6ImhhbG8yIiwiaWF0IjoxNjg5Njg1MjEwfQ.up9JwcXASZLeuGUbWbMRF90ifRjFfYm2MSXdsK6kZjQ

{
    "nama" : "barang9",
    "harga" : 1000,
    "stok" : 20,
    "perusahaan_id" : "ABC",
    "kode" : "DEB"
}

###
DELETE http://localhost:3000/barang/36207441-18ec-473f-945d-6e543b125ae2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzdkMTQyNS02N2Q0LTQ0NzgtOGJmNy04YWMwZGQyYjEzYzgiLCJ1c2VybmFtZSI6ImhhbG8yIiwiaWF0IjoxNjg5Njg1MjEwfQ.up9JwcXASZLeuGUbWbMRF90ifRjFfYm2MSXdsK6kZjQ

###
GET http://localhost:3000/perusahaan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzdkMTQyNS02N2Q0LTQ0NzgtOGJmNy04YWMwZGQyYjEzYzgiLCJ1c2VybmFtZSI6ImhhbG8yIiwiaWF0IjoxNjg5Njg1MjEwfQ.up9JwcXASZLeuGUbWbMRF90ifRjFfYm2MSXdsK6kZjQ

###
GET http://localhost:3000/perusahaan/694f2b3e-3a8f-427c-a78f-c89e412fa151
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzdkMTQyNS02N2Q0LTQ0NzgtOGJmNy04YWMwZGQyYjEzYzgiLCJ1c2VybmFtZSI6ImhhbG8yIiwiaWF0IjoxNjg5Njg1MjEwfQ.up9JwcXASZLeuGUbWbMRF90ifRjFfYm2MSXdsK6kZjQ

###
POST http://localhost:3000/perusahaan
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzdkMTQyNS02N2Q0LTQ0NzgtOGJmNy04YWMwZGQyYjEzYzgiLCJ1c2VybmFtZSI6ImhhbG8yIiwiaWF0IjoxNjg5Njg1MjEwfQ.up9JwcXASZLeuGUbWbMRF90ifRjFfYm2MSXdsK6kZjQ

{
    "nama": "PT Ivan Unyu",
    "alamat": "Jalan Arjuna no. 12",
    "no_telp": "08123456789",
    "kode": "ABX"
} 